# Generated by Django 2.2.2 on 2019-06-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='ques',
        ),
    ]
